name: C/C++ debug macos

on:
  push:
    branches:
      - debug_macos

jobs:
  build:

    runs-on: macos-latest
    
    env:
      EXEC_NAME: "${{ github.event.repository.name }}"
      DBL_NAME: "${{ github.event.repository.name }}/${{ github.event.repository.name }}"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'debug_macos'
    - name: update submodule profiles
      working-directory: ./resources/profiles
      run: git submodule update --init
    - id: lowercase_repo
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.event.repository.name }}
    - name: set exec name
      if: ${{ github.event.repository.name != 'Slic3r' }}
      uses: allenevans/set-env@v2.0.0
      with:
        EXEC_NAME: "${{ steps.lowercase_repo.outputs.lowercase }}"
    - name: change date in version
      run: |
        sed "s/+UNKNOWN/_$(date '+%F')/" version.inc > version.date.inc
        mv version.date.inc version.inc
    - name: mkdir in deps
      run: mkdir deps/build
    - name: cmake deps
      working-directory: ./deps/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13"
    - name: make deps
      working-directory: ./deps/build
      run: make
    - name: ls libs
      working-directory: ./deps/build
      run: ls ./destdir/usr/local/lib
    - name: rename wxscintilla
      working-directory: ./deps/build/destdir/usr/local/lib
      run: cp libwxscintilla-3.1.a libwx_osx_cocoau_scintilla-3.1.a
    - name: ls libs
      working-directory: ./deps/build
      run: ls ./destdir/usr/local/lib
    - name: clean deps
      working-directory: ./deps/build
      run: rm -rf dep_*
    - name: mkdir build
      run: mkdir build
    - name: cmake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="$PWD/../deps/build/destdir/usr/local" -DCMAKE_OSX_DEPLOYMENT_TARGET="10.13" -DSLIC3R_STATIC=1
    - name: make ${{ github.event.repository.name }}
      working-directory: ./build
      run: make Slic3r
    - name: make .mo
      working-directory: ./build
      run: make gettext_po_to_mo
    - name: update Info.plist
      working-directory: ./build/src
      run: sed "s/+UNKNOWN/_$(date '+%F')/" Info.plist >Info.date.plist
    - name: create directory and copy into it
      working-directory: ./build
      run: |
        mkdir pack
        mkdir pack/${{ github.event.repository.name }}
        mkdir pack/${{ env.DBL_NAME }}.app
        mkdir pack/${{ env.DBL_NAME }}.app/Contents
        mkdir pack/${{ env.DBL_NAME }}.app/Contents/_CodeSignature
        mkdir pack/${{ env.DBL_NAME }}.app/Contents/Frameworks
        mkdir pack/${{ env.DBL_NAME }}.app/Contents/MacOS
    - name: copy Resources
      working-directory: ./build
      run: |
        cp -Rf ../resources pack/${{ env.DBL_NAME }}.app/Contents/Resources
        cp pack/${{ env.DBL_NAME }}.app/Contents/Resources/icons/${{ github.event.repository.name }}.icns pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app/Contents/resources/${{ github.event.repository.name }}.icns
        cp src/Info.date.plist pack/${{ github.event.repository.name }}/${{ github.event.repository.name }}.app/Contents/Info.plist
        echo -n -e 'APPL????\x0a' > PkgInfo
        cp PkgInfo pack/${{ env.DBL_NAME }}.app/Contents/PkgInfo
#        echo -n -e '\xff\xfeAPPL\x3f\x00\x3f\x00\x3f\x00\x3f\x00\x0a\x00' > PkgInfo
    - name: copy bin and do not let it lower case
      working-directory: ./build
      run: |
        cp -f src/${{ env.EXEC_NAME }} pack/${{ env.DBL_NAME }}.app/Contents/MacOS/${{ github.event.repository.name }}
        chmod u+x pack/${{ env.DBL_NAME }}.app/Contents/MacOS/${{ github.event.repository.name }}
        tar -cvf ${{ github.event.repository.name }}.tar pack/${{ github.event.repository.name }}
    - name: create dmg
      working-directory: ./build
      run: |
        hdiutil create -ov -fs HFS+ -volname "${{ github.event.repository.name }}" -srcfolder "pack/${{ github.event.repository.name }}" temp.dmg
        hdiutil convert temp.dmg -format UDZO -o ${{ github.event.repository.name }}.dmg
#    - name: signing Resources (creating CodeResources inside _CodeSignature)
#      working-directory: .
#      run: codesign -s <identity> Resources
# maybe i should just try to do that on a separate pc and copy the file here, more secure as a signing process.
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos.tar
        path: build/${{ github.event.repository.name }}.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos_debug.dmg
        path: build/${{ github.event.repository.name }}.dmg
